sudo: false
language: java
jdk:
- oraclejdk8
addons:
  apt:
    packages:
    - oracle-java8-installer
before_install:
- openssl aes-256-cbc -K $encrypted_d640c57cb8c6_key -iv $encrypted_d640c57cb8c6_iv
  -in deploy_key.enc -out deploy_key -d
- npm install -g gitbook-cli
install:
- mvn install -U -Dmaven.test.skip=true
script:
- mvn test
after_success: bash ./scripts/gh-deploy.sh
notifications:
  email: false
  slack:
    secure: lyUdygbmGJHoMPTIYbKYnVEnDlJQoVKK5kjYaU7eKxLJf0/o68k9ca7h5IqkCceTBmD4Lgi7rtvD8rWp+RfiN2vE4hcWt8xNTGq7JfteyN50FFNwG7zOM6o9mzYg0S1WuD9gKx2UIU656fbUeGip/+mrmmbsbzqsnBJ4RxdOGfa+giHoDc1j3b7guHZGkTXlagDcN23sQvfQ5Fn3Heu0csykx6sFoWntAMDmFJBwD6bVcWbCsssZdvI1JouhTwP3HY6I18qBQ7XhIqJQ4IqabFYbZc9cBZzuk2InwsugrYq3VMo1CDUln/6AEFAjzYsDfbV6S084qakpyHXe5gH3CGbTLazr4JgvRN3yhVYPXDGmTQN8OHOzLVslitxdxm1oFB/HajIxI+c/15etrKM6zh7i5IrALZ2l9eg9POlpuWC/11E+nTO9duWvFV3tkui0U6IDTHdSg3aZVcOA5GtDq8Ou5pZMv5FZqSEJMQ6Mh3sz4OW3oh/Hw8sJxp0ZzoYvNP0TdjAHl2ULAtXinvJOLQ7d4QlLAaw8HERd1DeCfsKprNCTg7/2unYUi+n8CeEZnOzg82jAN6b/Y4xXITTfyR+PIaXpH9cuIzFI8ezE/6ANldwSDzLWnpzaaE8ThsOGF6debwD961kH/UTqQ747CrvXCE6xCF7lP9i6YtlYhII=
env:
  global:
  - ENCRYPTION_LABEL: d640c57cb8c6 
  - COMMIT_AUTHOR_EMAIL: kvndrsslr@gmail.com
